version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}

networks:
  my_custom_network:
    external: true

services:
  nginx:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    ports:
      - "8005:8005"
      - "8010:8010"
    networks:
      - my_custom_network
